apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "100"
      work_mem: "8MB"
  
  bootstrap:
    initdb:
      database: app_db
      owner: admin
      secret:
        name: db-user-credentials
      postInitSQL:
        - ALTER USER admin CREATEDB CREATEROLE;
        - CREATE DATABASE openbao_db OWNER admin;
  
  storage:
    storageClass: standard
    size: 500Mi
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  affinity:
    podAntiAffinityType: required
  
  backup:
    barmanObjectStore:
      destinationPath: s3://postgres-backups/
      endpointURL: http://minio-application.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: db-user-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: db-user-credentials
          key: ACCESS_SECRET_KEY
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: true
    retentionPolicy: "1d"
