apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  instances: 3
  
  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "100"
      work_mem: "8MB"
  
  bootstrap:
    initdb:
      database: app_db
      owner: admin
      secret:
        name: db-user-credentials
  
  storage:
    size: 10Gi
    storageClass: standard
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  affinity:
    podAntiAffinityType: preferred
