apiVersion: v1
kind: Secret
metadata:
  name: db-user-credentials
  namespace: postgres
type: Opaque
stringData:
  username: admin
  password: admin
  ACCESS_KEY_ID: admin
  ACCESS_SECRET_KEY: admin123456
