apiVersion: batch/v1
kind: Job
metadata:
  name: init-openbao-db
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-db
        image: postgres:16
        env:
        - name: PGHOST
          value: "postgres-cluster-rw.default.svc.cluster.local"
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-user-credentials
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-credentials
              key: password
        - name: PGDATABASE
          value: "app_db"
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h $PGHOST -p $PGPORT -U $PGUSER; do
            echo "Waiting for database connection..."
            sleep 2
          done
          
          echo "Creating openbao_db database..."
          psql -v ON_ERROR_STOP=1 <<-EOSQL
            SELECT 'CREATE DATABASE openbao_db'
            WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'openbao_db')\gexec
          EOSQL
          
          echo "openbao_db database initialized successfully"
