apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tranvutuan2001/uk-essen.git
    targetRevision: main
    path: infra/busybox
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
