apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tranvutuan2001/uk-essen.git'
    targetRevision: HEAD
    path: infra/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
