apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-transit
  namespace: argocd
spec:
  sources:
    - repoURL: https://openbao.github.io/openbao-helm
      chart: openbao
      targetRevision: 0.4.0
      helm:
        valueFiles:
            - $rootrepo/infra/openbao/transit-values.yaml
    - repoURL: https://github.com/tranvutuan2001/uk-essen.git
      targetRevision: HEAD
      ref: rootrepo
  destination:
    server: https://kubernetes.default.svc
    namespace: openbao
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
