apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://openbao.github.io/openbao-helm
      chart: openbao
      targetRevision: 0.25.0
      helm:
        valueFiles:
            - $rootrepo/infra/openbao/values.yaml
    
    - repoURL: 'https://github.com/tranvutuan2001/uk-essen.git'
      targetRevision: HEAD
      ref: rootrepo

    # Additional raw manifests (RBAC for transit auth init container)
    - repoURL: 'https://github.com/tranvutuan2001/uk-essen.git'
      targetRevision: HEAD
      path: infra/openbao/manifests
    
  destination:
    server: https://kubernetes.default.svc
    namespace: openbao
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
